version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb_data:/data/db"
    networks:
      - mynetwork

  go-app:
    image: gabriel3035/ittalent-clone-hackathon:1.0
    container_name: go-app
    ports:
      - "9080:9080"
    environment:
      MONGO_DB_HOST: mongodb
    depends_on:
      - mongodb
    networks:
      - mynetwork

  linux-client:
    image: ubuntu:latest
    container_name: linux-client
    command: tail -f /dev/null
    networks:
      - mynetwork

networks:
  mynetwork:
